### ISSUE TITLE
When Lua 5.2 support?

### ISSUE THREAD

**Issue by pass86** [unknownworlds/decoda#16]
When Lua 5.2 support?
I think many people want this.

**Comment by benoit-germain** [comment]
I am working on Lua 5.2 support and I believe that it is coming together nicely. However, looking at the other pending pull requests I think that some conflicts are to be expected with my changes if they ever get accepted in the master branch. The easiest way for all would be for those pull requests to be either integrated or rejected so that I can take care of the merge on a clean basis instead of simply adding yet another pull request to the list.

Of course, this supposes that someone will do something about the existing pull requests, which hasn't happened for several months...

**Comment by maxmcguire** [comment]
Hi Benoit,

I wasn't aware those pull requests were pending, I'll take a look at them.

Thanks,

Max

**Comment by benoit-germain** [comment]
I believe that I'm pretty much done with the port. All that remains to do now is actually submit the pull request.

**Comment by madmaxoft** [comment]
Question: When Lua 5.2 support is switched on, will Lua 5.1 still be supported, or will we have to migrate all our projects as well? Any chance of keeping both versions supported?

**Comment by benoit-germain** [comment]
Yes I've done it right :). Decoda still supports 5.1, and Lua 4.0 for that matter, unless I broke something.

**Comment by jazzbre** [comment]
Hi Benoit,
is Lua 5.2 support already commited because I can't find it?
Thanks

**Comment by lengbing** [comment]
wanna new ide just for lua5.2

**Comment by benoit-germain** [comment]
No, it is not committed yet. I'll get around to that eventually if nothing moves regarding the current pull requests. I experience freezes sometimes though so maybe I got something wrong with the debug hooks, since this changed a bit between 5.1 and 5.2.

**Comment by jazzbre** [comment]
Cool :) Would it be possible to commit it as a new branch or something so I could help you fix it faster?

**Comment by benoit-germain** [comment]
See pull request #19.

**Comment by benoit-germain** [comment]
I guess this one can be closed?
